export const Chairperson = [
  {
    id: 1,
    title: " Dr. M Rushwaya",
    image: "",
    position: "",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 2,
    title: "Mr. K. C. Katsande",
    image: "",
    position: "",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
];

export const Committee = [
  {
    id: 1,
    title: "Mr. W. L. Manungo",
    image: "",
    position: "",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 2,
    title: "Dr. M. C. Bimha",
    image: "",
    position: "",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
];

export const Team = [
  {
    id: 1,
    title: "Mr. M. Muzite",
    image: "/mutize.jpeg",
    position: "Acting Executive Secretary",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 2,
    title: "Mr. G. Murehwa",
    image: "/murehwa.jpg",
    position: "Director Economics and Research",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 3,
    title: "Mrs. A. Kawiri",
    image: "/kawiri.jpeg",
    position: "Director Finance,Administration & H.R",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 4,
    title: "Ms. S. Makiwa",
    image: "",
    position: "H.R and Administration Manager",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 5,
    title: "Mr. G. Gowere",
    image: "/gowere.jpg",
    position: "Manager Policy Analysis",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 6,
    title: "Mr. J. Dzama",
    image: "/dzama.jpeg",
    position: "Manager Economic Research",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 6,
    title: "Mr. B. Machiya",
    image: "",
    position: "Senior Economist",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 7,
    title: "Mr. P. Wilo",
    image: "",
    position: "Economist",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 8,
    title: "Mr. S. Maponga",
    image: "",
    position: "Economist",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 9,
    title: "Mrs. M. Nyoni",
    image: "/nyoni.jpg",
    position: "Executive Assistant",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 10,
    title: "Mrs. M.C. Masukusa",
    image: "/masukusa.jpeg",
    position: "Executive Assistant",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 11,
    title: "Ms. R. Njerere",
    image: "/njerere.jpg",
    position: "Accounting Assistant",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 12,
    title: "Ms. M. Masukume",
    image: "",
    position: "Receptionist",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 13,
    title: "Mr. M. Mudavanhu",
    image: "/mudavanhu.jpg",
    position: "Driver",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 14,
    title: "Ms. M. Mapira",
    image: "",
    position: "Executive Assistant",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
];

export const Colors = [];
