export const Chairperson = [
  {
    id: 1,
    name: " Dr. M Rushwaya",
    imageUrl: "",
    title: "",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 2,
    name: "Mr. K. C. Katsande",
    imageUrl: "",
    title: "",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
];

export const Committee = [
  {
    id: 1,
    name: "Mr. W. L. Manungo",
    imageUrl: "",
    title: "",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 2,
    name: "Dr. M. C. Bimha",
    imageUrl: "",
    title: "",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
];

export const Team = [
  {
    id: 1,
    name: "Mr. M. Muzite",
    imageUrl: "/mutize.jpeg",
    title: "Acting Executive Secretary",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 2,
    name: "Mr. G. Murehwa",
    imageUrl: "/murehwa.jpg",
    title: "Director Economics and Research",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 3,
    name: "Mrs. A. Kawiri",
    imageUrl: "/kawiri.jpeg",
    title: "Director Finance,Administration & H.R",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 4,
    name: "Ms. S. Makiwa",
    imageUrl: "",
    title: "H.R and Administration Manager",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 5,
    name: "Mr. G. Gowere",
    imageUrl: "/gowere.jpg",
    title: "Manager Policy Analysis",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 6,
    name: "Mr. J. Dzama",
    imageUrl: "/dzama.jpeg",
    title: "Manager Economic Research",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 6,
    name: "Mr. B. Machiya",
    imageUrl: "",
    title: "Senior Economist",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 7,
    name: "Mr. P. Wilo",
    imageUrl: "",
    title: "Economist",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 8,
    name: "Mr. S. Maponga",
    imageUrl: "",
    title: "Economist",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 9,
    name: "Mrs. M. Nyoni",
    imageUrl: "/nyoni.jpg",
    title: "Executive Assistant",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 10,
    name: "Mrs. M.C. Masukusa",
    imageUrl: "/masukusa.jpeg",
    title: "Executive Assistant",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 11,
    name: "Ms. R. Njerere",
    imageUrl: "njerere.jpg",
    title: "Accounting Assistant",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 12,
    name: "Ms. M. Masukume",
    imageUrl: "",
    title: "Receptionist",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 13,
    name: "Mr. M. Mudavanhu",
    imageUrl: "mudavanhu.jpg",
    title: "Driver",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
  {
    id: 14,
    name: "Ms. M. Mapira",
    imageUrl: "",
    title: "Executive Assistant",
    desc: "",
    fbLink: "",
    twitterLink: "",
    gmail: "",
  },
];

export const Colors = [];
